services:
  mysql:
    image: mysql:latest
    container_name: Inventorydb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: condabu
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306" # Expose MySQL port to the host
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
