package org.condabu.notificationservice.common;

public enum SmsType {
    ACCOUNT_OPENING,
    ORDER_CREATED,
    ORDER_CANCELLED,
    ORDER_DELIVERED,
    INVOICE_SENT,
    LOW_STOCK,
    ORDER_DISPATCHED,
    PAYMENT_REMINDER,
    NEW_PRODUCT_ARRIVAL,
    MAINTENANCE_SCHEDULE,
    ORDER_CONFIRMATION
}
